### ISSUE TITLE
Cannot read property 'profileToken' of undefined

### ISSUE THREAD

**Issue by strarsis** [agsh/onvif#119]
When trying to connect to the camera an error occurs:
````
TypeError: Cannot read property 'profileToken' of undefined
    at Cam.getStreamUri ([...]node_modules/onvif/lib/media.js:802:67)
    at Cam.<anonymous> ([...]index.js:11:8)
    at Cam.<anonymous> ([...]node_modules/onvif/lib/cam.js:128:19)
    at Cam.<anonymous> ([...]node_modules/onvif/lib/media.js:729:14)
    at parseSOAPString ([...]node_modules/onvif/lib/utils.js:98:3)
    at IncomingMessage.<anonymous> ([...]node_modules/onvif/lib/cam.js:206:4)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
````

**Comment by strarsis** [comment]
Apparently I used incorrect ONVIF credentials (used Web UI credentials instead).
But instead a proper error should be thrown that authorization failed.

**Comment by agsh** [comment]
@strarsis It seems that your cam sends a response for the getCapabilities method even with the wrong credentials or it hasn't got any active source.
You can check `cam.activeSources` property before calling any media method. Also, I've added a new event `warning` in the `master` branch. So you can check this trouble by subscribing:
```js
cam.on('warning' msg => { console.warning(msg); });
```

**Comment by dcruveiller** [comment]
Hey i have also this problem and i'm sure i put the right login and hostname informations.
Here is my output:
```
/Users/d.cruveiller/Documents/TIB/vscode/onvif/node_modules/onvif/lib/media.js:1003
                                '<ProfileToken>' + (options.profileToken || this.activeSource.profileToken) + '</ProfileToken>' +

TypeError: Cannot read property 'profileToken' of undefined
    at Cam.getStreamUri (/Users/d.cruveiller/Documents/TIB/vscode/onvif/node_modules/onvif/lib/media.js:1003:67)
    at Cam.<anonymous> (/Users/d.cruveiller/Documents/TIB/vscode/onvif/app.js:10:10)
    at Cam.<anonymous> (/Users/d.cruveiller/Documents/TIB/vscode/onvif/node_modules/onvif/lib/cam.js:159:20)
    at Cam.<anonymous> (/Users//d.cruveiller/Documents/TIB/vscode/onvif/node_modules/onvif/lib/cam.js:365:14)
    at parseSOAPString (/Users/d.cruveiller/Documents/TIB/vscode/onvif/node_modules/onvif/lib/utils.js:108:3)
    at IncomingMessage.<anonymous> (/Users//d.cruveiller/Documents/TIB/vscode/onvif/node_modules/onvif/lib/cam.js:267:4)
```
of this code:
```
var Cam = require('onvif').Cam;

new Cam({
    hostname: '192.168.1.78',
    username: 'admin',
    password: 'admin'
  }, function(err) {
    // if (err) { console.log(err); return; }
    // this.absoluteMove({x: 1, y: 1, zoom: 1});
    this.getStreamUri({protocol: 'RTSP'}, function(err, stream) {
        console.log("CONNECTED");
    });
});
```

But if i uncomment the ``// if (err) { console.log(err); return; } `` I get:
```
Error: Wrong ONVIF SOAP response
    at /Users/d.cruveiller/Documents/TIB/vscode/onvif/node_modules/onvif/lib/utils.js:74:15
    at Parser.<anonymous> (/Users/d.cruveiller/Documents/TIB/vscode/onvif/node_modules/xml2js/lib/parser.js:308:18)
    at Parser.emit (events.js:315:20)
    at SAXParser.onerror (/Users/d.cruveiller/Documents/TIB/vscode/onvif/node_modules/xml2js/lib/parser.js:123:26)
    at emit (/Users/d.cruveiller/Documents/TIB/vscode/onvif/node_modules/sax/lib/sax.js:624:35)
    at error (/Users/d.cruveiller/Documents/TIB/vscode/onvif/node_modules/sax/lib/sax.js:653:5)
    at strictFail (/Users/d.cruveiller/Documents/TIB/vscode/onvif/node_modules/sax/lib/sax.js:677:7)
    at beginWhiteSpace (/Users/d.cruveiller/Documents/TIB/vscode/onvif/node_modules/sax/lib/sax.js:951:7)
    at SAXParser.write (/Users/d.cruveiller/Documents/TIB/vscode/onvif/node_modules/sax/lib/sax.js:1006:11)
    at Parser.exports.Parser.Parser.parseString (/Users/d.cruveiller/Documents/TIB/vscode/onvif/node_modules/xml2js/lib/parser.js:323:31)
```

**Comment by qaz6209031** [comment]
Same issue here, I am sure I put the right hostname and authentication information, but I got the same result.

**Comment by Roulbac** [comment]
Same here

**Comment by ricmoo** [comment]
FYI. This is was happening to me because the port was incorrect. My camera uses 8080 by default, and that made everything move along swimmingly. :)

**Comment by distante** [comment]
Maybe this helps someone, I got this error because I was using `http://123.my.camera.ip`, and I should just use `123.my.camera.ip`
