### ISSUE TITLE
Cannot use PTZ

### ISSUE THREAD

**Issue by schw4rzlicht** [agsh/onvif#132]
I am currently trying to control a Reolink C1 Pro with onvif. I can log in and I do see stuff like video sources, capabilities etc. but I am not able to change pan/tilt even though it's listed in the capabilites.

I am using this code snippet:
```javascript
camInstance.absoluteMove({x: 0, y: 0}, function (err) {
    console.warn(err);
});
```

And I am catching this error:
```
Error: ONVIF SOAP Fault: {"value":"SOAP-ENV:Sender"}
    at /Users/julian/WebstormProjects/cctv-bridge/node_modules/onvif/lib/utils.js:91:13
    at Parser.<anonymous> (/Users/julian/WebstormProjects/cctv-bridge/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (events.js:210:5)
    at SAXParser.onclosetag (/Users/julian/WebstormProjects/cctv-bridge/node_modules/xml2js/lib/parser.js:262:26)
    at emit (/Users/julian/WebstormProjects/cctv-bridge/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/Users/julian/WebstormProjects/cctv-bridge/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/Users/julian/WebstormProjects/cctv-bridge/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/Users/julian/WebstormProjects/cctv-bridge/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/Users/julian/WebstormProjects/cctv-bridge/node_modules/xml2js/lib/parser.js:323:31)
    at Parser.parseString (/Users/julian/WebstormProjects/cctv-bridge/node_modules/xml2js/lib/parser.js:5:59)
```

**Comment by RogerHardiman** [comment]
Not all cameras support AbsoluteMove.

Many cameras support ContinuousMove where you tell the camera to start moving and then tell the camera when to Stop.

You need to check the PTZ Capabilities for your camera. The response to GetProfiles will mention Absolute, Relative and Continuous
