### ISSUE TITLE
Unable to start listening to event stream (Error: You should create pull-point subscription first!)

### ISSUE THREAD

**Issue by arjenvanderknijff** [agsh/onvif#183]
Hi,

Since today I'am unable to start a listner on events from my camera. The log gave me the following stacktrace

Error: You should create pull-point subscription first!
at Cam.pullMessages (/root/.node-red/node_modules/onvif/lib/events.js:188:10)
at Cam._eventPull (/root/.node-red/node_modules/onvif/lib/events.js:309:9)
at Cam.<anonymous> (/root/.node-red/node_modules/onvif/lib/events.js:100:13)
at parseSOAPString (/root/.node-red/node_modules/onvif/lib/utils.js:108:3)
at IncomingMessage.<anonymous> (/root/.node-red/node_modules/onvif/lib/cam.js:270:4)
at IncomingMessage.emit (events.js:203:15)
at endReadableNT (_stream_readable.js:1145:12)
at process._tickCallback (internal/process/next_tick.js:63:19)

The camera (reolink410) does support pullpoint. Furthermore, the current setup was working earlier. 

Hoping someone can give me a hint towards a resolution.  Thanks in advance, KR
Arjen

**Comment by arjenvanderknijff** [comment]
After doing half a day of debuging I ended up in creating a issue here. As a final resort I just reboted the camera and 'magically' everything started working again.
