### ISSUE TITLE
gotoHomePosition error

### ISSUE THREAD

**Issue by erineyes** [agsh/onvif#211]
hi there~
during your module using npm install onvif or npm install agsh/onvif,
when i call gotoHomePosition following error is occur

TypeError: Cannot read property 'bind' of undefined
    at Cam.gotoHomePosition (/home/ubuntu/workspace/onvif_ptz_server/node_modules/onvif/lib/ptz.js:124:15)
    at Cam.<anonymous> (/home/ubuntu/workspace/onvif_ptz_server/index.js:50:30)
    at Cam.<anonymous> (/home/ubuntu/workspace/onvif_ptz_server/node_modules/onvif/lib/cam.js:171:26)
    at Cam.<anonymous> (/home/ubuntu/workspace/onvif_ptz_server/node_modules/onvif/lib/media.js:990:15)
    at /home/ubuntu/workspace/onvif_ptz_server/node_modules/onvif/lib/utils.js:103:6
    at Parser.<anonymous> (/home/ubuntu/workspace/onvif_ptz_server/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (events.js:198:13)
    at SAXParser.onclosetag (/home/ubuntu/workspace/onvif_ptz_server/node_modules/xml2js/lib/parser.js:262:26)
    at emit (/home/ubuntu/workspace/onvif_ptz_server/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/home/ubuntu/workspace/onvif_ptz_server/node_modules/sax/lib/sax.js:629:5)

you test it on      
   "host": "125.130.243.205",
    "port": 8000,
    "id": "admin",
    "pwd": "admin"
 Camera Vendor is Bolin.

**Comment by erineyes** [comment]
it is my fault..
