### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by tetherit** [agsh/onvif#66]
When I try to run a discovery using the latest version (installed with npm install agsh/onvif#dev), I get the following:

```coffeescript
# discover.coffee
onvif = require('onvif')
onvif.Discovery.on 'device', (cam) ->
  console.log('Camera!')

onvif.Discovery.probe()                     
```

```
# coffee discover.coffee
Camera!
Camera!
Camera!
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property '0' of undefined
  at Cam.<anonymous> (/dev/onvif/node_modules/onvif/lib/cam.js:255:103)
  at /dev/onvif/node_modules/onvif/lib/utils.js:94:5
  at Parser.<anonymous> (/dev/onvif/node_modules/xml2js/lib/xml2js.js:489:18)
  at emitOne (events.js:96:13)
  at Parser.emit (events.js:188:7)
  at Object.onclosetag (/dev/onvif/node_modules/xml2js/lib/xml2js.js:447:26)
  at emit (/dev/onvif/node_modules/sax/lib/sax.js:640:35)
  at emitNode (/dev/onvif/node_modules/sax/lib/sax.js:645:5)
  at closeTag (/dev/onvif/node_modules/sax/lib/sax.js:905:7)
  at Object.write (/dev/onvif/node_modules/sax/lib/sax.js:1449:13)
  at Parser.exports.Parser.Parser.parseString (/dev/onvif/node_modules/xml2js/lib/xml2js.js:508:31)
  at Parser.parseString (/dev/onvif/node_modules/xml2js/lib/xml2js.js:7:59)
  at Object.exports.parseString (/dev/onvif/node_modules/xml2js/lib/xml2js.js:540:19)
  at parseSOAPString (/dev/onvif/node_modules/onvif/lib/utils.js:62:9)
  at IncomingMessage.<anonymous> (/dev/onvif/node_modules/onvif/lib/cam.js:202:4)
  at emitNone (events.js:91:20)
  at IncomingMessage.emit (events.js:185:7)
  at endReadableNT (_stream_readable.js:974:12)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)
```

Any ideas?

**Comment by xanview** [comment]
When I add console.log(data[0]['getSystemDateAndTimeResponse'][0]['systemDateAndTime'][0]) to line 255 of node_modules/onvif/lib/cam.js it returns nothing. Maybe there should be an if condition that checks this exists before relying on it?

**Comment by picharras** [comment]
Hi, a hard code and temporal fix:

`var dt = data[0]['getSystemDateAndTimeResponse'][0]['systemDateAndTime'][0] == '' ? {date: {year: 2016, month: 1, day: 3}, time: {hour: 21, minute: 28, second: 35}} : linerase(data[0]['getSystemDateAndTimeResponse'][0]['systemDateAndTime'][0]['UTCDateTime'][0]);`

**Comment by chriswiggins** [comment]
Closing out old issue
