### ISSUE TITLE
When trying to access events, getting Cannot read property 'address' of undefined

### ISSUE THREAD

**Issue by tetherit** [agsh/onvif#72]
I have this code

```javascript
var Cam = require('onvif').Cam;
var cam = new Cam({
  hostname: '192.168.1.108',
  username: 'admin',
  password: 'admin'
}, function(err) {
  console.log('CONNECTED');
  console.log(this)

  this.on('event', function(camMessage){console.log(camMessage)});
});
```

When I run it I get:

```
$ node onvif_events.js
CONNECTED
Cam {
  hostname: '192.168.1.108',
  username: 'admin',
  password: 'admin',
  port: 80,
  path: '/onvif/device_service',
  timeout: 120000,
  preserveAddress: false,
  events: {},
  timeShift: -822,
  capabilities: 
   { analytics: 
      { XAddr: 'http://192.168.1.108/onvif/analytics_service',
        ruleSupport: true,
        analyticsModuleSupport: true },
     device: 
      { XAddr: 'http://192.168.1.108/onvif/device_service',
        network: [Object],
        system: [Object],
        IO: [Object],
        security: [Object] },
     events: 
      { XAddr: 'http://192.168.1.108/onvif/event_service',
        WSSubscriptionPolicySupport: false,
        WSPullPointSupport: false,
        WSPausableSubscriptionManagerInterfaceSupport: false },
     imaging: { XAddr: 'http://192.168.1.108/onvif/imaging_service' },
     media: 
      { XAddr: 'http://192.168.1.108/onvif/media_service',
        streamingCapabilities: [Object],
        extension: [Object] },
     extension: { deviceIO: [Object], extensions: [Object] } },
  uri: 
   { media: 
      Url {
        protocol: 'http:',
        slashes: true,
        auth: null,
        host: '192.168.1.108',
        port: null,
        hostname: '192.168.1.108',
        hash: null,
        search: null,
        query: null,
        pathname: '/onvif/media_service',
        path: '/onvif/media_service',
        href: 'http://192.168.1.108/onvif/media_service' },
     imaging: 
      Url {
        protocol: 'http:',
        slashes: true,
        auth: null,
        host: '192.168.1.108',
        port: null,
        hostname: '192.168.1.108',
        hash: null,
        search: null,
        query: null,
        pathname: '/onvif/imaging_service',
        path: '/onvif/imaging_service',
        href: 'http://192.168.1.108/onvif/imaging_service' },
     events: 
      Url {
        protocol: 'http:',
        slashes: true,
        auth: null,
        host: '192.168.1.108',
        port: null,
        hostname: '192.168.1.108',
        hash: null,
        search: null,
        query: null,
        pathname: '/onvif/event_service',
        path: '/onvif/event_service',
        href: 'http://192.168.1.108/onvif/event_service' },
     device: 
      Url {
        protocol: 'http:',
        slashes: true,
        auth: null,
        host: '192.168.1.108',
        port: null,
        hostname: '192.168.1.108',
        hash: null,
        search: null,
        query: null,
        pathname: '/onvif/device_service',
        path: '/onvif/device_service',
        href: 'http://192.168.1.108/onvif/device_service' },
     deviceIO: 
      Url {
        protocol: 'http:',
        slashes: true,
        auth: null,
        host: '192.168.1.108',
        port: null,
        hostname: '192.168.1.108',
        hash: null,
        search: null,
        query: null,
        pathname: '/onvif/deviceIO_service',
        path: '/onvif/deviceIO_service',
        href: 'http://192.168.1.108/onvif/deviceIO_service' } },
  videoSources: [ { '$': [Object], framerate: 25, resolution: [Object] } ],
  profiles: 
   [ { '$': [Object],
       name: 'MediaProfile_Channel1_MainStream',
       videoSourceConfiguration: [Object],
       audioSourceConfiguration: [Object],
       videoEncoderConfiguration: [Object],
       audioEncoderConfiguration: [Object],
       videoAnalyticsConfiguration: [Object],
       metadataConfiguration: [Object] },
     { '$': [Object],
       name: 'MediaProfile_Channel1_SubStream1',
       videoSourceConfiguration: [Object],
       audioSourceConfiguration: [Object],
       videoEncoderConfiguration: [Object],
       audioEncoderConfiguration: [Object],
       videoAnalyticsConfiguration: [Object],
       metadataConfiguration: [Object] } ],
  defaultProfiles: 
   [ { '$': [Object],
       name: 'MediaProfile_Channel1_MainStream',
       videoSourceConfiguration: [Object],
       audioSourceConfiguration: [Object],
       videoEncoderConfiguration: [Object],
       audioEncoderConfiguration: [Object],
       videoAnalyticsConfiguration: [Object],
       metadataConfiguration: [Object] } ],
  activeSources: 
   [ { sourceToken: '000',
       profileToken: 'MediaProfile000',
       encoding: 'H264',
       width: 1920,
       height: 1080,
       fps: undefined,
       bitrate: 2048 } ],
  defaultProfile: 
   { '$': { token: 'MediaProfile000', fixed: true },
     name: 'MediaProfile_Channel1_MainStream',
     videoSourceConfiguration: 
      { '$': [Object],
        name: 'VideoSourceConfig_Channel1',
        useCount: 2,
        sourceToken: '000',
        bounds: [Object] },
     audioSourceConfiguration: 
      { '$': [Object],
        name: 'AudioSourceConfig_Channel1',
        useCount: 2,
        sourceToken: '000' },
     videoEncoderConfiguration: 
      { '$': [Object],
        name: 'VideoEncoderConfig_Channel1_MainStream',
        useCount: 1,
        encoding: 'H264',
        resolution: [Object],
        quality: 4,
        rateControl: [Object],
        H264: [Object],
        multicast: [Object],
        sessionTimeout: 'PT60S' },
     audioEncoderConfiguration: 
      { '$': [Object],
        name: 'AudioEncoderConfig_Channel1_MainStream',
        useCount: 1,
        encoding: 'AAC',
        bitrate: 384,
        sampleRate: 48,
        multicast: [Object],
        sessionTimeout: 'PT60S' },
     videoAnalyticsConfiguration: 
      { '$': [Object],
        name: 'VideoAnalyticsConfig_Channel1',
        useCount: 2,
        analyticsEngineConfiguration: [Object],
        ruleEngineConfiguration: [Object] },
     metadataConfiguration: 
      { '$': [Object],
        name: 'MetadataConfig_Channel1',
        useCount: 2,
        PTZStatus: [Object],
        events: [Object],
        analytics: true,
        multicast: [Object],
        sessionTimeout: 'PT60S' } },
  activeSource: 
   { sourceToken: '000',
     profileToken: 'MediaProfile000',
     encoding: 'H264',
     width: 1920,
     height: 1080,
     fps: undefined,
     bitrate: 2048 } }
rtsp://192.168.1.108:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
events.js:163
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'address' of undefined
    at Cam.<anonymous> (/Users/test/script/node_modules/onvif/lib/events.js:207:40)
    at Array.forEach (native)
    at Cam.<anonymous> (/Users/test/script/node_modules/onvif/lib/events.js:205:31)
    at Cam.<anonymous> (/Users/test/script/node_modules/onvif/lib/events.js:151:12)
    at /Users/test/script/node_modules/onvif/lib/utils.js:94:5
    at Parser.<anonymous> (/Users/test/script/node_modules/xml2js/lib/xml2js.js:489:18)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:191:7)
    at SAXParser.onclosetag (/Users/test/script/node_modules/xml2js/lib/xml2js.js:447:26)
    at emit (/Users/test/script/node_modules/sax/lib/sax.js:640:35)
    at emitNode (/Users/test/script/node_modules/sax/lib/sax.js:645:5)
```

Any ideas?

EDIT: This is a Dahua camera, full details:
Device TypeIPC-HDW4431EM-AS
Software Version2.460.0000.1.R, Build Date: 2016-10-25
WEB Version3.2.1.388722
ONVIF Version2.42

**Comment by enovz** [comment]
The events module checks an array of messages 
`message.subscriptionReference.address === this.events.subscription.subscriptionReference.address.href`

_commenting out this statement produces a event with data_

**Comment by RogerHardiman** [comment]
The fix from @enovz has been included in a recent commit.
